import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import UserBlock from "~/components/userblock";
import UsersBar from "~/components/users";
import { api } from "~/utils/api";
import LogInPage from "~/components/login";
import InputBar from "~/components/input";
import ChatView from "~/components/chatview";
const Home: NextPage = () => {
  const { data, isLoading: postsLoading } = api.post.getAll.useQuery();
  const user = useSession();
  if (!user.data) return <LogInPage></LogInPage>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#043d0c] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center px-4  ">
          <ChatView userId={user.data.user.id}></ChatView>
          <InputBar />
          <div className="absolute left-0 top-0">
            <UserBlock />
            <UsersBar />
          </div>

          <br></br>
        </div>
      </main>
    </>
  );
};

export default Home;
