import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import UserBlock from "~/components/userblock";
import UsersBar from "~/components/users";
import { api } from "~/utils/api";

import InputBar from "~/components/input";
import ChatView from "~/components/chatview";

const Home: NextPage = () => {
  const { data, isLoading: postsLoading } = api.post.getAll.useQuery();
  const user = useSession();
  const userId = user.data ? user.data.user.id : "";
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex max-h-screen  grid-cols-2  items-center justify-center bg-gradient-to-b from-[#043d0c] to-[#15162c]">
        <div className="container flex max-h-screen flex-col items-center justify-center rounded-md border-x-2 border-lime-400 bg-black px-4  ">
          <div className="flex grid-cols-2 text-xs">
            <div className="flex justify-start">
              <UserBlock />
            </div>
            <div className="flex justify-end">
              <UsersBar />
            </div>
          </div>
          <ChatView userId={userId}></ChatView>
          <InputBar />
        </div>
      </main>
    </>
  );
};

export default Home;
